# Generated by Django 3.2.12 on 2022-04-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220314_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_pic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic_directory_path'),
        ),
    ]
