# Generated by Django 3.2.9 on 2022-03-15 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagepost',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='publish',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagepost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
