# Generated by Django 3.2.12 on 2022-04-01 11:38

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220315_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=post.models.post_directory_path),
        ),
    ]
